"""The route to somewhere the car has already been. Pure, no rclpy.

Exploring produces a path full of detours: every dead end was entered, backed
out of, and entered no more. This module reads the map that exploration built
and emits the route a car should drive if it already knew the answer -- which is
the same thing `route_exec.load_route` reads, so driving it needs no new code at
all.

## Why this is breadth-first, and why that is nearly a formality

In a maze without loops there is exactly one route from the start to any node,
so "the shortest route" and "the only route" are the same list, and
`graph_builder.identify` has already stored it: the node's key IS its route. A
search is not needed to find it.

It is written as a search anyway, for two reasons worth more than the fifteen
lines it costs. It is correct when the key stops being the route -- which is
precisely what happens once the maze has a loop and `identify` grows a
pose-derived component -- and it reads the edges rather than the keys, so it
cannot silently disagree with the map about what the car actually drove. A
planner that returned `goal_key` directly would keep working after the graph
became wrong.

**Edge lengths are not consulted.** In a tree they cannot change the answer, and
claiming a shortest-*distance* route from a cost nothing has ever been optimised
against would be a measurement-shaped thing that is not a measurement. When loops
arrive, this is where Dijkstra replaces the queue -- and by then the lengths will
have been validated by `analysis/map_from_log.py`.

## What the saving actually is

Not distance over an alternative route -- there is no alternative. It is the
detours: the corridors the explored run drove twice, once in and once back out,
that the planned run does not drive at all. `saving()` reports exactly that, so
the number in the report is the one the demo shows.
"""

from collections import deque

class NoRouteError(ValueError):
    """There is no path from the start to the requested node."""


def route_to(maze, key):
    """Breadth-first from the start to `key` -> the turns to drive there.

    Returns [] for the start itself. Raises `NoRouteError` when the node is
    unreachable, which on a map built by driving means the map is corrupt --
    every node in it was reached by a car -- and is worth a loud failure rather
    than an empty route that a car would happily drive straight through.
    """
    if key == maze.root:
        return []
    if key not in maze.nodes:
        raise NoRouteError(f"node {key!r} is not in the map")

    seen = {maze.root}
    queue = deque([(maze.root, [])])
    while queue:
        here, turns = queue.popleft()
        for edge in maze.neighbours(here):
            if edge.to_key in seen:
                continue
            route = turns + [edge.turn]
            if edge.to_key == key:
                return route
            seen.add(edge.to_key)
            queue.append((edge.to_key, route))

    raise NoRouteError(
        f"node {key!r} is in the map but nothing leads to it. The map is "
        f"inconsistent: every node in it was reached by driving.")


def route_to_goal(maze):
    """The turns from the start to the goal.

    Raises if the goal was never found -- an exploration run that ended without
    it has nothing to plan, and emitting an empty route file would send the car
    down the first corridor with no turn at all.
    """
    key = maze.goal_key
    if key is None:
        raise NoRouteError(
            "no goal in the map: the run ended without finding one, so there "
            "is no route to plan. Check `goal_state` in the trial log.")
    return route_to(maze, key)


def saving(maze, driven_turns):
    """(planned, driven, detours avoided) -- what the plan is worth.

    `driven_turns` is every turn the exploring car actually committed to,
    including the ones into dead ends. The difference is the point of the
    exercise and is the figure to quote.
    """
    planned = route_to_goal(maze)
    return len(planned), len(driven_turns), len(driven_turns) - len(planned)


def format_route(turns, note=""):
    """Turns -> route-file text, in the format `route_exec.parse_route` reads.

    Round-tripping through that parser is deliberate: a generated route gets the
    same validation as a hand-written one, so a planner bug surfaces as a parse
    error at the desk rather than as a car turning the wrong way.
    """
    lines = ["# Generated by cone_nav.guidance.planner -- do not hand-edit."]
    if note:
        lines.extend("# " + part for part in note.splitlines())
    lines.extend(turns)
    return "\n".join(lines) + "\n"


def write_route(turns, path, note=""):
    """Write a route file and return the text written."""
    text = format_route(turns, note)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    return text
